name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        architecture: 'x86'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller -w --name=HawkingClicker ./src/main.py

    - name: Get version from tag
      id: get_version
      run: |
        echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

    - name: Compress build artifacts
      run: |
        cd dist
        7z a HawkingClicker-windows-x86-${{ steps.get_version.outputs.version }}.zip HawkingClicker

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/HawkingClicker-windows-x86-${{ steps.get_version.outputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
